main:
  params: [args]
  steps:
    - init:
        assign:
          - error_response:
              - error: "未提供有效輸入。請提供文字內容"
              - timestamp: ${time.format(sys.now())}
          - execution_id: ${sys.get_env("WORKFLOW_EXECUTION_ID")}
          - timestamp: ${time.format(sys.now())}
          - base_url: "https://asia-east1-genasl.cloudfunctions.net"

    - validateInput:
        switch:
          - condition: ${args == null}
            next: returnError
          - condition: ${"text" in args}
            assign:
              - text_for_gloss:
                  - ${args.text}
            next: convertToGloss
          - condition: ${true}
            next: returnError

    - returnError:
        return: ${error_response}

    - convertToGloss:
        try:
          call: http.post
          args:
            url: ${base_url + "/text-to-gloss"}
            body:
              text: ${text_for_gloss[0]}
            auth:
              type: OIDC
          result: gloss_response
        except:
          as: e
          steps:
            - handleGlossException:
                return:
                  - error: "Gloss 轉換失敗"
                  - details: ${e}
                  - stage: "gloss_conversion"
                  - timestamp: ${timestamp}

    - getVideos:
        try:
          call: http.post
          args:
            url: ${base_url + "/gloss-to-video"}
            body:
              gloss: ${gloss_response.body.gloss}
            auth:
              type: OIDC
          result: video_response
        except:
          as: e
          steps:
            - handleVideoException:
                return:
                  error: "影片查詢失敗"
                  details: ${e}
                  stage: "video_lookup"
                  timestamp: ${timestamp}

    - prepareResult:
        assign:
          - result:
              - success: true
              - original_input: ${args}
              - gloss_response: ${gloss_response.body}
              - video_response: ${video_response.body}
              - execution_info:
                  - execution_id: ${execution_id}
                  - timestamp: ${timestamp}

    - returnResult:
        return: ${result}